# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=260)),
                ('lastname', models.CharField(max_length=260)),
                ('rollno', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
                ('micro_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=5)),
                ('stu_year', models.IntegerField()),
                ('stu_sem', models.IntegerField()),
            ],
        ),
    ]
