# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='attendence',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
