# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0002_studentmodel_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='stu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='digital_college', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
