# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_studentmodel_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depts', models.CharField(max_length=12)),
            ],
        ),
    ]
