# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_departmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='d_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
