# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_remove_departmentmodel_d_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
            ],
        ),
    ]
