# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_yearmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearmodel',
            name='y_depts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Years', to='digital.DepartmentModel'),
            preserve_default=False,
        ),
    ]
