# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0011_ounotesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ounotesmodel',
            name='pdfname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
