# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0012_ounotesmodel_pdfname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ounotesmodel',
            name='dept',
        ),
        migrations.DeleteModel(
            name='OuNotesModel',
        ),
    ]
