# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0013_auto_20210105_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuNotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oufiles', models.FileField(default='no pdf', null=True, upload_to='')),
                ('pdfname', models.CharField(max_length=120)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ou_dept', to='digital.DepartmentModel')),
            ],
        ),
    ]
