# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0015_auto_20210105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ounotesmodel',
            name='oufiles',
            field=models.FileField(default='no pdf', null=True, upload_to=''),
        ),
    ]
