# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0016_auto_20210105_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPapersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='no image', null=True, upload_to='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_images_dept', to='digital.DepartmentModel')),
            ],
        ),
    ]
