# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0018_previouspapersmodel_paper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouspapersmodel',
            name='slug',
            field=models.SlugField(default='kedar', max_length=264),
            preserve_default=False,
        ),
    ]
