# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0020_gallarymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearmodel',
            name='years',
        ),
    ]
