# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0021_remove_yearmodel_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearmodel',
            name='years',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
