# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0024_auto_20210107_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facuiltymodel',
            name='dept',
            field=models.CharField(max_length=120),
        ),
    ]
