# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0025_auto_20210107_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearmodel',
            old_name='y_depts',
            new_name='hod_depts',
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='hod_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='hod_pno',
            field=models.CharField(default='kedar', max_length=12),
            preserve_default=False,
        ),
    ]
