# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0026_auto_20210107_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearmodel',
            name='hod_depts',
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='hod_dept',
            field=models.CharField(default='kedar', max_length=120),
            preserve_default=False,
        ),
    ]
