# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-08 07:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0027_auto_20210107_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_date', models.DateTimeField(default=datetime.datetime(2021, 1, 15, 7, 4, 11, 606833, tzinfo=utc))),
                ('total_books', models.IntegerField()),
                ('borrowed_books', models.IntegerField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_college', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
