# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0032_auto_20210108_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymodel',
            name='rollno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
