# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0033_librarymodel_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableAndSyllabusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.FileField(default='no timetable', null=True, upload_to='')),
                ('syllabus', models.FileField(default='no syllabus', null=True, upload_to='')),
            ],
        ),
    ]
