# Generated by Django 3.1.5 on 2021-02-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0034_timetableandsyllabusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('result', models.FileField(default='no result', null=True, upload_to='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_model', to='digital.departmentmodel')),
            ],
        ),
    ]
